schemaVersion: 1.1.0
locale: "en"
groupings:
  - title: "Deploy Nginx service using Container Instances"
    variables:
    - region
    - compartment_ocid
    - vcn_id
    - subnet_id
    - container_instance

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to create all resources
    required: true

  vcn_id:
    type: oci:core:vcn:id
    title: Target VCN
    description: The target vcn id where to create all resources
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  subnet_id:
    type: oci:core:subnet:id
    title: Target Subnet
    description: The target subnet id where to create all resources
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_id}
 
  container_instance:
    type: json
    title: Container Instance definition
    description: Container Instance definition
    required: true

